# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f61f94006794a81bc02223d374426a5948b2eb6d7ff7f8f9aa7661a0a7bfcf8e0392cb8c965c18133ccab6c7fb495ce3a7525a39dacc1ce0a20e9831ae11267

test:
  secret_key_base: 91488a4f5acfc076c32d74ef3fee368082265e1489f945249152a0dd91bf8ae3701907e58a43f2c3048f564e65c52aa3963377b126ca6e06f2b8520bd62b99cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
